---
title: "iNaturalist"
author: "Shale"
date: "2/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen = 20)
```

# Data Setup

```{r}
librarian::shelf(
  digest, dplyr, DT, glue, purrr, readr, stringr, tidyr, here, keras, tensorflow, reticulate)

# path to folder containing species directories of images
dir_src  <- "/courses/EDS232/inaturalist-2021/train_mini"
dir_dest <- "~/inat"
dir.create(dir_dest, showWarnings = F)

# get list of directories, one per species (n = 10,000 species)
dirs_spp <- list.dirs(dir_src, recursive = F, full.names = T)
n_spp <- length(dirs_spp)

# set seed (for reproducible results) 
# just before sampling (otherwise get different results)
# based on your username (unique amongst class)
Sys.info()[["user"]] %>% 
  digest::digest2int() %>% 
  set.seed()
i10 <- sample(1:n_spp, 10)

# show the 10 indices sampled of the 10,000 possible 
i10

```

```{r}
# show the 10 species directory names
basename(dirs_spp)[i10]
```
```{r}
i2 <- i10[1:2]
basename(dirs_spp)[i2]
```

```{r, eval=FALSE}
# setup data frame with source (src) and destination (dest) paths to images
idata <- tibble(
  set     = c(rep("spp2", 2), rep("spp10", 10)),
  dir_sp  = c(dirs_spp[i2], dirs_spp[i10]),
  tbl_img = map(dir_sp, function(dir_sp){
    tibble(
      src_img = list.files(dir_sp, full.names = T),
      subset  = c(rep("train", 30), rep("validation", 10), rep("test", 10))) })) %>% 
  unnest(tbl_img) %>% 
  mutate(
    sp       = basename(dir_sp),
    img      = basename(src_img),
    dest_img = glue("{dir_dest}/{set}/{subset}/{sp}/{img}"))

# show source and destination for first 10 rows of tibble
# idata %>% 
#   select(src_img, dest_img)

idata %>% 
  pwalk(function(src_img, dest_img, ...){
    dir.create(dirname(dest_img), recursive = T, showWarnings = F)
    file.copy(src_img, dest_img) })
```

Tried a thing:

```{r, eval=FALSE}
# filepath labels
train2_dir = file.path(dir_dest, "spp2/train")
test2_dir = file.path(dir_dest, "spp2/test")
validation2_dir = file.path(dir_dest, "spp2/validation")
train10_dir = file.path(dir_dest, "spp10/train")
test10_dir = file.path(dir_dest, "spp10/test")
validation10_dir = file.path(dir_dest, "spp10/validation")

# Resize images for binary classification
datagen_resizr <- image_data_generator(rescale = 1/255)

tensor_gen <- function(img_subset) {
  
  img_dir2 = paste0(img_subset + "2_dir")
  img_dir10 = paste0(img_subset + "10_dir")
    
    flow_images_from_directory(
  img_dir2,
  datagen_resizr,
  target_size = c(150, 150),
  batch_size = 10,
  class_mode = "binary"
  )
    
    generator10 <- flow_images_from_directory(
  img_dir10,
  datagen_resizr,
  target_size = c(150, 150),
  batch_size = 10,
  class_mode = "binary"
  )
}
```

Manually:

```{r}
# filepath labels
train_dir = here("inat/spp2/train")
test_dir = here("inat/spp2/test")
validation_dir = here("inat/spp2/validation")
train10_dir = here("inat/spp10/train")
test10_dir = here("inat/spp10/test")
validation10_dir = here("inat/spp10/validation")

# Resize images for binary classification
datagen <- image_data_generator(rescale = 1/255)

# Avoid overfitting
train_datagen <- image_data_generator(
  rescale = 1/255,
  rotation_range = 40,
  width_shift_range = 0.2,
  height_shift_range = 0.2,
  shear_range = 0.2,
  zoom_range = 0.2,
  horizontal_flip = TRUE,
  fill_mode = "nearest"
)

train_generator <- flow_images_from_directory(
  train_dir,
  train_datagen,
  target_size = c(150, 150),
  batch_size = 30,
  class_mode = "binary"
)

test_generator <- flow_images_from_directory(
  test_dir,
  datagen,
  target_size = c(150, 150),
  batch_size = 10,
  class_mode = "binary"
)

val_generator <- flow_images_from_directory(
  validation_dir,
  datagen,
  target_size = c(150, 150),
  batch_size = 10,
  class_mode = "binary"
)
```

# Binary Neural Net

```{r}
nn_model <- keras_model_sequential() %>% 
  layer_dense(units = 16, activation = "relu", input_shape = c(150,150,3)) %>% 
  layer_dense(units = 16, activation = "relu") %>% 
  layer_flatten() %>%
  layer_dense(units =  1, activation = "sigmoid")
```

```{r}
nn_model %>% compile(
  optimizer = "rmsprop",
  loss      = "binary_crossentropy",
  metrics   = c("accuracy"))
```

```{r}
nn_history <- nn_model %>% fit(
  train_generator,
  steps_per_epoch = 1,
  epochs = 30,
  validation_data = val_generator,
  validation_steps = 1
)
```

```{r}
plot(nn_history)

nn_model %>% predict(test_generator)
```

# Binary Convolutional Neural Net

```{r}
conv_model <- keras_model_sequential() %>%
layer_conv_2d(filters = 32, kernel_size = c(3, 3), activation = "relu",
input_shape = c(150, 150, 3)) %>%
layer_max_pooling_2d(pool_size = c(2, 2)) %>%
layer_conv_2d(filters = 64, kernel_size = c(3, 3), activation = "relu") %>% layer_max_pooling_2d(pool_size = c(2, 2)) %>%
layer_conv_2d(filters = 128, kernel_size = c(3, 3), activation = "relu") %>% layer_max_pooling_2d(pool_size = c(2, 2)) %>%
layer_conv_2d(filters = 128, kernel_size = c(3, 3), activation = "relu") %>% layer_max_pooling_2d(pool_size = c(2, 2)) %>%
layer_flatten() %>%
layer_dense(units = 512, activation = "relu") %>%
layer_dense(units = 1, activation = "sigmoid")
```

```{r}
conv_model %>% compile(
  loss = "binary_crossentropy",
  optimizer = "rmsprop",
  metrics = c("acc")
)
```

```{r}
c_history <- conv_model %>% fit(
  train_generator,
  steps_per_epoch = 1,
  epochs = 30,
  validation_data = val_generator,
  validation_steps = 1
)
```

```{r}
plot(c_history)

conv_model %>% predict(test_generator)
```

## Comparison of NN/CNN for Binary Classification:
**The **

# Multiclass Neural Net

```{r}
train10_generator <- flow_images_from_directory(
  train10_dir,
  train_datagen,
  target_size = c(150, 150),
  batch_size = 30,
  class_mode = "categorical"
)

test10_generator <- flow_images_from_directory(
  test10_dir,
  datagen,
  target_size = c(150, 150),
  batch_size = 10,
  class_mode = "categorical"
)

val10_generator <- flow_images_from_directory(
  validation10_dir,
  datagen,
  target_size = c(150, 150),
  batch_size = 10,
  class_mode = "categorical"
)
```

```{r}
model10 <- keras_model_sequential() %>% 
  layer_dense(units = 64, activation = "relu", input_shape = c(150,150,3)) %>% 
  layer_dense(units = 64, activation = "relu") %>% 
  layer_dense(units = 10, activation = "softmax")
```

```{r}
model10 %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("accuracy")
)
```

```{r}
history10 <- model10 %>% fit(
  train10_generator,
  steps_per_epoch = 1,
  epochs = 30,
  validation_data = val10_generator,
  validation_steps = 1
)
```

```{r}
plot(history10)

model10 %>% predict(test10_generator)
```

# Multiclass Convolutional Neural Net

```{r}

```

## Comparison of NN/CNN for Categorical (n=10) Classification
**The **